# SPDX-FileCopyrightText: 2025-present A2A Net <hello@a2anet.com>
#
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from google.adk.tools.base_tool import BaseTool
from google.genai import types as genai_types

from adk_code_mode.tools import namespacing, stubs
from adk_code_mode.tools.normaliser import ResolvedTool


class _SchemaTool(BaseTool):
    def __init__(
        self,
        name: str,
        *,
        description: str,
        schema: dict[str, object] | None = None,
    ) -> None:
        super().__init__(name=name, description=description)
        self._schema = schema or {}

    def _get_declaration(self) -> genai_types.FunctionDeclaration | None:
        return genai_types.FunctionDeclaration(
            name=self.name,
            description=self.description,
            parameters_json_schema=self._schema,
        )


def _build(nts: list[tuple[BaseTool, object | None]]) -> list[namespacing.NamespacedTool]:
    resolved = [ResolvedTool(tool=t, toolset=ts) for t, ts in nts]  # type: ignore[arg-type]
    return namespacing.build(resolved)


def _stub_source(nt: namespacing.NamespacedTool) -> str:
    return stubs.render_tool_source(stubs.render_tool(nt))


def test_render_tool_emits_typed_signature_and_call() -> None:
    tool = _SchemaTool(
        "send_message",
        description="Send a message.",
        schema={
            "type": "object",
            "properties": {
                "channel": {"type": "string", "description": "Channel ID."},
                "text": {"type": "string"},
                "thread_ts": {"type": "string", "nullable": True},
            },
            "required": ["channel", "text"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "def send_message(*, channel: str, text: str" in source
    assert "thread_ts: str | None" in source
    assert "return _call('send_message'" in source
    assert '"""Send a message.' in source


def test_render_tool_enum_becomes_literal() -> None:
    tool = _SchemaTool(
        "pick",
        description="Pick one.",
        schema={
            "type": "object",
            "properties": {"color": {"type": "string", "enum": ["red", "green"]}},
            "required": ["color"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "color: Literal['red', 'green']" in source


def test_render_tree_root_reexports_top_level_tools_only() -> None:
    """Top-level tools are re-exported so ``from tools import <name>`` works.
    Namespaced tools are not re-exported from the root — the model imports
    them via ``from tools.<namespace> import <name>``."""
    a = _SchemaTool("ping", description="Ping.", schema={"type": "object"})
    b = _SchemaTool("pong", description="Pong.", schema={"type": "object"})
    ns = _build([(a, None), (b, None)])
    files = stubs.render_tree(ns)
    paths = [f.path for f in files]
    assert "__init__.py" in paths
    assert "ping.py" in paths
    assert "pong.py" in paths
    root = next(f for f in files if f.path == "__init__.py")
    assert "from .ping import ping" in root.source
    assert "from .pong import pong" in root.source
    assert "Generated by adk-code-mode" in root.source


def test_render_tree_root_is_marker_when_only_namespaced_tools() -> None:
    """When all tools are namespaced, root is a single-line marker — no eager
    re-exports of the namespaced surface (avoids loading every stub on a
    bare ``import tools``)."""

    class _FakeToolset:
        name = "slack"
        tool_name_prefix = ""

    a = _SchemaTool("ping", description="Ping.", schema={"type": "object"})
    ns = _build([(a, _FakeToolset())])
    files = stubs.render_tree(ns)
    root = next(f for f in files if f.path == "__init__.py")
    assert "from " not in root.source
    assert "import" not in root.source
    assert "Generated by adk-code-mode" in root.source


def test_schema_anyof_becomes_pep604_union() -> None:
    tool = _SchemaTool(
        "x",
        description="",
        schema={
            "type": "object",
            "properties": {"thing": {"anyOf": [{"type": "string"}, {"type": "integer"}]}},
            "required": ["thing"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "thing: str | int" in source
    assert "Union[" not in source


def test_render_tool_omits_unset_optional_args() -> None:
    tool = _SchemaTool(
        "lookup",
        description="Lookup a record.",
        schema={
            "type": "object",
            "properties": {
                "record_id": {"type": "string"},
                "include_archived": {"type": "boolean"},
            },
            "required": ["record_id"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "_MISSING = object()" in source
    assert "include_archived: bool | None = _MISSING" in source
    assert "if include_archived is not _MISSING:" in source
    assert "_args['include_archived'] = include_archived" in source


def test_render_tool_optional_with_default_is_conditional_and_documented() -> None:
    """Optional params with a schema default still go through ``_MISSING`` so the
    host-side tool can apply its own default on omission. The schema default is
    surfaced in the docstring instead of being baked into the signature."""
    tool = _SchemaTool(
        "fetch",
        description="Fetch a record.",
        schema={
            "type": "object",
            "properties": {
                "expand": {
                    "type": "boolean",
                    "default": False,
                    "description": "Whether to expand nested fields.",
                },
            },
            "required": [],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "expand: bool | None = _MISSING" in source
    assert "expand: bool = False" not in source
    assert "if expand is not _MISSING:" in source
    assert "_args['expand'] = expand" in source
    assert "(default: False)" in source


def test_render_tool_sanitises_keyword_parameter_names() -> None:
    tool = _SchemaTool(
        "search",
        description="Search.",
        schema={
            "type": "object",
            "properties": {"from": {"type": "string"}},
            "required": ["from"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "def search(*, from_: str) -> Any:" in source
    assert "'from': from_," in source


def test_render_tool_rejects_parameter_name_collisions() -> None:
    tool = _SchemaTool(
        "lookup",
        description="Lookup.",
        schema={
            "type": "object",
            "properties": {
                "user-id": {"type": "string"},
                "user_id": {"type": "string"},
            },
            "required": ["user-id", "user_id"],
        },
    )
    ns = _build([(tool, None)])
    try:
        _stub_source(ns[0])
    except ValueError as exc:
        assert "both map to Python parameter 'user_id'" in str(exc)
    else:
        raise AssertionError("expected parameter collision to raise")


def test_render_tool_required_with_default_keeps_signature_default() -> None:
    """Required params with a schema default remain unconditionally forwarded
    and keep the schema default visible in the signature."""
    tool = _SchemaTool(
        "ping",
        description="Ping.",
        schema={
            "type": "object",
            "properties": {"retries": {"type": "integer", "default": 3}},
            "required": ["retries"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "retries: int = 3" in source
    assert "_args: dict[str, Any] = {" in source
    assert "'retries': retries," in source


def test_rendered_tool_catalog_signature_uses_ellipsis() -> None:
    """Catalog target hides the ``_MISSING`` sentinel behind ``...``."""
    tool = _SchemaTool(
        "lookup",
        description="Lookup.",
        schema={
            "type": "object",
            "properties": {
                "record_id": {"type": "string"},
                "include_archived": {"type": "boolean"},
            },
            "required": ["record_id"],
        },
    )
    ns = _build([(tool, None)])
    rt = stubs.render_tool(ns[0])
    sig = rt.signature_for("catalog")
    assert "include_archived: bool | None = ..." in sig
    assert "_MISSING" not in sig
