# SPDX-FileCopyrightText: 2025-present A2A Net <hello@a2anet.com>
#
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from google.adk.tools.base_tool import BaseTool
from google.genai import types as genai_types

from adk_code_mode.tools import namespacing, stubs
from adk_code_mode.tools.normaliser import ResolvedTool


class _SchemaTool(BaseTool):
    def __init__(
        self,
        name: str,
        *,
        description: str,
        schema: dict[str, object] | None = None,
    ) -> None:
        super().__init__(name=name, description=description)
        self._schema = schema or {}

    def _get_declaration(self) -> genai_types.FunctionDeclaration | None:
        return genai_types.FunctionDeclaration(
            name=self.name,
            description=self.description,
            parameters_json_schema=self._schema,
        )


def _build(nts: list[tuple[BaseTool, object | None]]) -> list[namespacing.NamespacedTool]:
    resolved = [ResolvedTool(tool=t, toolset=ts) for t, ts in nts]  # type: ignore[arg-type]
    return namespacing.build(resolved)


def _stub_source(nt: namespacing.NamespacedTool) -> str:
    return stubs.render_tool_source(stubs.render_tool(nt))


def test_render_tool_emits_typed_signature_and_call() -> None:
    tool = _SchemaTool(
        "send_message",
        description="Send a message.",
        schema={
            "type": "object",
            "properties": {
                "channel": {"type": "string", "description": "Channel ID."},
                "text": {"type": "string"},
                "thread_ts": {"type": "string", "nullable": True},
            },
            "required": ["channel", "text"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "def send_message(*, channel: str, text: str" in source
    assert "thread_ts: str | None" in source
    assert "return _call('send_message'" in source
    assert '"""Send a message.' in source


def test_render_tool_enum_becomes_literal() -> None:
    tool = _SchemaTool(
        "pick",
        description="Pick one.",
        schema={
            "type": "object",
            "properties": {"color": {"type": "string", "enum": ["red", "green"]}},
            "required": ["color"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "color: Literal['red', 'green']" in source


def test_render_tree_root_reexports_top_level_tools_only() -> None:
    """Top-level tools are re-exported so ``from tools import <name>`` works.
    Namespaced tools are not re-exported from the root — the model imports
    them via ``from tools.<namespace> import <name>``."""
    a = _SchemaTool("ping", description="Ping.", schema={"type": "object"})
    b = _SchemaTool("pong", description="Pong.", schema={"type": "object"})
    ns = _build([(a, None), (b, None)])
    files = stubs.render_tree(ns)
    paths = [f.path for f in files]
    assert "__init__.py" in paths
    assert "ping.py" in paths
    assert "pong.py" in paths
    root = next(f for f in files if f.path == "__init__.py")
    assert "from .ping import ping" in root.source
    assert "from .pong import pong" in root.source
    assert "Generated by adk-code-mode" in root.source


def test_render_tree_root_is_marker_when_only_namespaced_tools() -> None:
    """When all tools are namespaced, root is a single-line marker — no eager
    re-exports of the namespaced surface (avoids loading every stub on a
    bare ``import tools``)."""

    class _FakeToolset:
        name = "slack"
        tool_name_prefix = ""

    a = _SchemaTool("ping", description="Ping.", schema={"type": "object"})
    ns = _build([(a, _FakeToolset())])
    files = stubs.render_tree(ns)
    root = next(f for f in files if f.path == "__init__.py")
    assert "from " not in root.source
    assert "import" not in root.source
    assert "Generated by adk-code-mode" in root.source


def test_schema_anyof_becomes_pep604_union() -> None:
    tool = _SchemaTool(
        "x",
        description="",
        schema={
            "type": "object",
            "properties": {"thing": {"anyOf": [{"type": "string"}, {"type": "integer"}]}},
            "required": ["thing"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "thing: str | int" in source
    assert "Union[" not in source


def test_render_tool_omits_unset_optional_args() -> None:
    tool = _SchemaTool(
        "lookup",
        description="Lookup a record.",
        schema={
            "type": "object",
            "properties": {
                "record_id": {"type": "string"},
                "include_archived": {"type": "boolean"},
            },
            "required": ["record_id"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "_MISSING = object()" in source
    assert "include_archived: bool | None = _MISSING" in source
    assert "if include_archived is not _MISSING:" in source
    assert "_args['include_archived'] = include_archived" in source


def test_render_tool_optional_with_default_is_conditional_and_documented() -> None:
    """Optional params with a schema default still go through ``_MISSING`` so the
    host-side tool can apply its own default on omission. The schema default is
    surfaced in the docstring instead of being baked into the signature."""
    tool = _SchemaTool(
        "fetch",
        description="Fetch a record.",
        schema={
            "type": "object",
            "properties": {
                "expand": {
                    "type": "boolean",
                    "default": False,
                    "description": "Whether to expand nested fields.",
                },
            },
            "required": [],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "expand: bool | None = _MISSING" in source
    assert "expand: bool = False" not in source
    assert "if expand is not _MISSING:" in source
    assert "_args['expand'] = expand" in source
    assert "(default: False)" in source


def test_render_tool_sanitises_keyword_parameter_names() -> None:
    tool = _SchemaTool(
        "search",
        description="Search.",
        schema={
            "type": "object",
            "properties": {"from": {"type": "string"}},
            "required": ["from"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "def search(*, from_: str) -> Any:" in source
    assert "'from': from_," in source


def test_render_tool_rejects_parameter_name_collisions() -> None:
    tool = _SchemaTool(
        "lookup",
        description="Lookup.",
        schema={
            "type": "object",
            "properties": {
                "user-id": {"type": "string"},
                "user_id": {"type": "string"},
            },
            "required": ["user-id", "user_id"],
        },
    )
    ns = _build([(tool, None)])
    try:
        _stub_source(ns[0])
    except ValueError as exc:
        assert "both map to Python parameter 'user_id'" in str(exc)
    else:
        raise AssertionError("expected parameter collision to raise")


def test_render_tool_required_with_default_keeps_signature_default() -> None:
    """Required params with a schema default remain unconditionally forwarded
    and keep the schema default visible in the signature."""
    tool = _SchemaTool(
        "ping",
        description="Ping.",
        schema={
            "type": "object",
            "properties": {"retries": {"type": "integer", "default": 3}},
            "required": ["retries"],
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "retries: int = 3" in source
    assert "_args: dict[str, Any] = {" in source
    assert "'retries': retries," in source


def test_rendered_tool_catalog_signature_uses_ellipsis() -> None:
    """Catalog target hides the ``_MISSING`` sentinel behind ``...``."""
    tool = _SchemaTool(
        "lookup",
        description="Lookup.",
        schema={
            "type": "object",
            "properties": {
                "record_id": {"type": "string"},
                "include_archived": {"type": "boolean"},
            },
            "required": ["record_id"],
        },
    )
    ns = _build([(tool, None)])
    rt = stubs.render_tool(ns[0])
    sig = rt.signature_for("catalog")
    assert "include_archived: bool | None = ..." in sig
    assert "_MISSING" not in sig


def test_render_tool_expands_nested_object_properties() -> None:
    """An object parameter can only ever be typed ``dict[str, Any]``, so its keys
    reach the model through the docstring or not at all."""
    tool = _SchemaTool(
        "create_rule",
        description="Create a rule.",
        schema={
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "object",
                    "description": "Conditions that must all be satisfied (AND logic).",
                    "properties": {
                        "daysOfWeek": {
                            "type": "array",
                            "description": "Days of the week (1=Monday, 7=Sunday).",
                            "items": {"type": "integer", "minimum": 1, "maximum": 7},
                        },
                        "timeRange": {
                            "type": "object",
                            "properties": {
                                "from": {"type": "string", "example": "18:00"},
                                "to": {"type": "string"},
                            },
                        },
                    },
                }
            },
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "conditions: dict[str, Any] | None" in source
    assert "daysOfWeek: list[int] - Days of the week (1=Monday, 7=Sunday)." in source
    assert "items: minimum=1, maximum=7" in source
    assert "timeRange: dict[str, Any]" in source
    assert "from: str (example=18:00)" in source
    assert "to: str" in source


def test_render_tool_documents_validation_keywords() -> None:
    """No Python type expresses ``maxLength``/``pattern``; the docstring is the
    only route by which they reach the model."""
    tool = _SchemaTool(
        "save",
        description="Save.",
        schema={
            "type": "object",
            "properties": {
                "label": {"type": "string", "maxLength": 255},
                "code": {"type": "string", "pattern": "^[A-Z]{3}$"},
                "ratio": {"type": "number", "minimum": 0, "maximum": 1},
                "tags": {"type": "array", "minItems": 1, "items": {"type": "string"}},
            },
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "label: (maxLength=255)" in source
    assert "code: (pattern=^[A-Z]{3}$)" in source
    assert "ratio: (minimum=0, maximum=1)" in source
    assert "tags: (minItems=1)" in source


def test_render_tool_merges_allof_wrapped_ref() -> None:
    """``allOf: [$ref] + nullable`` is how OpenAPI 3.0 spells a nullable
    reference; without merging, the target's description and keys are lost."""
    tool = _SchemaTool(
        "book",
        description="Book.",
        schema={
            "type": "object",
            "properties": {
                "capacity": {
                    "allOf": [
                        {
                            "type": "object",
                            "description": "Min/max capacity range.",
                            "properties": {
                                "min": {"type": "integer"},
                                "max": {"type": "integer"},
                            },
                        }
                    ],
                    "nullable": True,
                }
            },
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "capacity: Min/max capacity range." in source
    assert "min: int" in source
    assert "max: int" in source


def test_render_tool_normalises_gemini_schema_casing() -> None:
    """With ADK's ``JSON_SCHEMA_FOR_FUNC_DECL`` off, schemas arrive via a Gemini
    ``types.Schema``: upper-cased types and snake_cased keywords."""
    tool = _SchemaTool(
        "gemini_shaped",
        description="Gemini shaped.",
        schema={
            "type": "OBJECT",
            "properties": {
                "label": {"type": "STRING", "max_length": 255},
                "nested": {
                    "type": "OBJECT",
                    "properties": {"count": {"type": "INTEGER", "minimum": 1.0}},
                },
            },
        },
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "label: str | None" in source
    assert "maxLength=255" in source
    assert "count: int (minimum=1)" in source


def test_render_tool_stops_recursing_on_self_referential_schema() -> None:
    """A schema that contains itself must not recurse forever."""
    node: dict[str, object] = {"type": "object", "description": "A tree node."}
    node["properties"] = {"child": node}
    tool = _SchemaTool(
        "walk", description="Walk.", schema={"type": "object", "properties": {"root": node}}
    )
    ns = _build([(tool, None)])
    source = _stub_source(ns[0])
    assert "root: A tree node." in source
    assert source.count("child: dict[str, Any]") == stubs._MAX_SCHEMA_DEPTH
